---
- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install python3
  apt:
    name: python3
    state: present

- name: Install virtualenv
  pip:
    name: virtualenv
    state: present

